---
# Clients for ecFlow Server
#  - use [] to provide empty list of clients
clients:
- kind: library
  protocol: udp
  host: localhost
  port: 8080

- kind: cli
  protocol: tcp

- kind: phony
  protocol: none
