---
# Clients for ecFlow Server
#  - use [] to provide empty list of clients
clients:
- protocol: udp
  host: localhost
  port: 8080
  kind: lib # (optional)

#- protocol: tcp
#  kind: cli

#- protocol: none
#  kind: echo
