---
# Connections to ecFlow Server
## Enabled Protocols: udp, cli (case sensitive); use [] to provide empty list of connections
connections:
- protocol: udp
  host: localhost
  port: 8080

# Log
## Enabled Log Level: None, Error, Warn, Info, Debug (case sensitive)
log_level: Info
